version: "3.6"
services:
    #Postgres database server
    postgres:
        image: overseaslabs/example-postgres:latest
        networks:
            - example_backend
        volumes:
            - example_postgres_db:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        env_file:
            - postgres.env
            - ureg.env
            - .env
            - kong.env
            - mailer.env

    #Redis server
    redis:
        image: redis:latest
        networks:
            - example_backend
        volumes:
            - example_postgres_db:/var/lib/postgresql/data/pgdata
        ports:
            - 6379:6379

    #User registry microservice
    ureg:
        image: overseaslabs/example-ureg:latest
        networks:
            - example_backend
            - example_frontend
        ports:
            - 8080:8080
        env_file:
            - ureg.env

    #Email sending and reporting
    mailer:
        image: overseaslabs/example-mailer:latest
        networks:
            - example_backend
        ports:
            - 8081:8080
        env_file:
            - mailer.env

volumes:
    #named volumes for storing the DB files
    example_postgres_db:

networks:
    example_frontend:
        driver: "overlay"
    example_backend:
        driver: "overlay"