version: "3.6"
services:
    #Postgres database server
    postgres:
        image: overseaslabs/example-postgres:1.0.0
        networks:
            - example_backend
        volumes:
            - example_postgres_db:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        env_file:
            - postgres.env
            - ureg.env
            - .env
            - kong.env
            - mailer.env
            - konga.env

    #Kong API gate
    kong:
        image: overseaslabs/example-kong:1.0.0
        env_file:
            - .env
            - kong.env
        networks:
            - example_backend
            - example_frontend
        ports:
            - 8000:8000
            - 8001:8001

    #Kong UI
    konga:
        image: pantsel/konga:latest
        env_file: konga.env
        networks:
            - example_backend
            - example_frontend
        ports:
            - 1337:1337

    #Redis server
    redis:
        image: redis:latest
        networks:
            - example_backend
        volumes:
            - example_redis:/var/lib/postgresql/data/pgdata
        ports:
            - 6379:6379

    #User registry microservice
    ureg:
        image: overseaslabs/example-ureg:1.0.0
        networks:
            - example_backend
            - example_frontend
        env_file:
            - ureg.env

    #Email sending and reporting
    mailer:
        image: overseaslabs/example-mailer:1.0.1
        networks:
            - example_backend
        env_file:
            - mailer.env

    #Web UI
    web:
        image: overseaslabs/example-web:1.0.0
        ports:
            - 80:8080
        networks:
            - example_backend
            - example_frontend

volumes:
    #named volumes for storing the DB files
    example_postgres_db:
    example_redis:

networks:
    example_frontend:
        driver: "overlay"
    example_backend:
        driver: "overlay"
